// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9Fu43dyV8ZNmGdaL2CmQY1Ke9ykfPCBQ',
    appId: '1:394708819581:web:53a743024161329ee19b14',
    messagingSenderId: '394708819581',
    projectId: 'flutteruzbek',
    authDomain: 'flutteruzbek.firebaseapp.com',
    storageBucket: 'flutteruzbek.appspot.com',
    measurementId: 'G-WTFZMJT12B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4vK-QfFhL-UtivuqE6vRekt8qM5Hn7i8',
    appId: '1:394708819581:android:19c70e70860065e3e19b14',
    messagingSenderId: '394708819581',
    projectId: 'flutteruzbek',
    storageBucket: 'flutteruzbek.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkBjVqPlq09b9IpzI3k6uWGVv7sVYNJxA',
    appId: '1:394708819581:ios:5efbfb0d6c962b79e19b14',
    messagingSenderId: '394708819581',
    projectId: 'flutteruzbek',
    storageBucket: 'flutteruzbek.appspot.com',
    androidClientId: '394708819581-inoclvscja1ns3u8klqlqh4p1q711agn.apps.googleusercontent.com',
    iosClientId: '394708819581-f2rd6anco3getvvv16ffffg36114er7l.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterUzbek',
  );
}
